### ISSUE TITLE
【Scanning Software】Optimization

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-desktop-environment#11]
现状：
1、系统默认集成的开源软件扫描易，界面丑、使用不流畅。
2、设备插入后检测时间长，有时需要10多秒。
目标：
1、与ukui3.0统一界面风格，提高使用流畅性和易用性。
提高设备检测速度，热插拔能没有延时的正确判断和处理。

**Comment by handsome-feng** [comment]
计划中。
