### ISSUE TITLE
【Kirin Assistant &System Repair Tool】Requirements

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-desktop-environment#13]
现状：缺少一个可靠的系统修复图形工具。
目标：开发一个系统自带的修复工具，需要样式美观、代码可读性强，支持插件开发，功能点需要包括磁盘检查和修复、磁盘清理、dpkg修复、grub修复、gpg修复、密码重置、权限修复等，当然，各个功能可以独立开发出对应的小工具。

**Comment by handsome-feng** [comment]
计划中。
