### ISSUE TITLE
[Calculator] requirements

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-desktop-environment#15]
目标：开发一个系统自带的计算器软件，需要简洁、样式美观、操作方式符合设计。
可以参考现有开源软件如gcalculator等代码

附：Win10自带计算器样式
![image](https://user-images.githubusercontent.com/39893452/87523622-bc61d900-c6b9-11ea-8036-cdc3025d9f01.png)

**Comment by handsome-feng** [comment]
计划中。
