### ISSUE TITLE
Impossible to type in Chinese

### ISSUE THREAD

**Issue by LAfricain** [ukui/ukui-desktop-environment#40]
I use Ubuntu Kylin in french and in Chinese. But if I want to type in chineses with ibus, I can change the keyboard, it's working in the menu when I search an apps, but it's not working neither with LibreOffice or Pluma, or any other software! This is really annoying.
I hope I'm in the right place for the issue.

I change fcitx for Ibus, because even fcitx doesn't work.

**Comment by h1antEn9** [comment]
At present, both fcitx and IBus have such problems. You can modify the priority of the desired input method through the configuration interface of fcitx. Switching to other languages still requires manual keyboard switching.

**Comment by LAfricain** [comment]
I solved the problem for ibus, some packages were missing. I installed ibus-pinyin, ibus-m17n, ibus-gtk3, ibus-libpinyin and it was working.

**Comment by h1antEn9** [comment]
We have also solved this problem on the latest system. You can use fcitx on later updated systems and you won't encounter this problem again.
