### ISSUE TITLE
[Information popup window] The interface does not implement the UKUI3.0 style

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-desktop-environment#8]
![image](https://user-images.githubusercontent.com/39893452/87520768-fd57ee80-c6b5-11ea-89dd-2530574d316d.png)
![image](https://user-images.githubusercontent.com/39893452/87520773-ff21b200-c6b5-11ea-9776-9bcfe6454136.png)

**Comment by handsome-feng** [comment]
已实现。
